### ISSUE TITLE
Translator for Add to Store Well

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Drillflow#42] opened 2018-11-02 19:21 UTC
Child of #33
Requires #18

The translator needs to be created to convert the object from source to destination. For DrillOps that will be WITSML 2.0.

This will require copying the object properties from one to another.

**Comment by randypitcherii** [comment] 2018-11-20 20:39
Duplicate of #92

**Comment by randypitcherii** [comment] 2018-11-27 16:34
UPDATE: 
The DoT API now works in WITSML 1.4.1.1 JSON, not 2.0.

Do this same task, but target WITSML 1.4.1.1 translation

**Comment by randypitcherii** [comment] 2018-11-27 18:35
BLOCKED - need a drilltest API to implement this against

**Closed** 2018-12-01 15:07 UTC
Labels: in progress
