### ISSUE TITLE
for all date time data types that do not have time zone info append Z

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Drillflow#188] opened 2018-12-13 14:37 UTC
Currently in 1.4.1.1 the time zone is required for every time stamp. The suggestion is that in the event that a time zone is not present, the Witsml Objects Library will append a Z to that value during serialization.

Child of #226

**Comment by randypitcherii** [comment] 2018-12-13 17:00
duplicate of #189

**Closed** 2019-01-15 16:18 UTC
Labels: WOL, duplicate, enhancement, todo
