### ISSUE TITLE
DEV: LOG: (URGENT) Add To Store Errors Out 

### ISSUE THREAD

**Issue by shehzadsidi** [hashmapinc/Drillflow#603] opened 2019-06-26 17:44 UTC
AddToStore for both Time and Depth errors in "Internal Server" response.  However, the object is actually being created.  The issue is with response:

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
   <soap:Body>
      <ns1:WMLS_AddToStoreResponse xmlns:ns1="http://www.witsml.org/message/120">
         <Result>-1</Result>
         <SuppMsgOut>{"message":"Internal Server Error"}</SuppMsgOut>
      </ns1:WMLS_AddToStoreResponse>
   </soap:Body>
</soap:Envelope>

**Comment by shehzadsidi** [comment] 2019-06-26 17:58
Request Log Object:
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://www.witsml.org/wsdl/120" xmlns:types="http://www.witsml.org/wsdl/120/encodedTypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <soap:Body soap:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
      <q1:WMLS_AddToStore xmlns:q1="http://www.witsml.org/message/120">
         <WMLtypeIn xsi:type="xsd:string">log</WMLtypeIn>
         <XMLin xsi:type="xsd:string"><![CDATA[<?xml version="1.0" encoding="utf-16"?>
		<logs xmlns="http://www.witsml.org/schemas/1series" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.witsml.org/schemas/1series  ../xsd_schemas/obj_log.xsd" version="1.4.1.1">
		<log uidWell="Energistics-well-0001" uidWellbore="Energistics-w1-wellbore-0001" uid="HM_43cc444f-f182-478e-ab8b-47909051d561">
		<nameWell>Well Energistics-well-0001</nameWell>
		<nameWellbore>Wellbore Energistics-w1-wellbore-0001</nameWellbore>
		<name>Log_HM_43cc444f-f182-478e-ab8b-47909051d561</name>
		<serviceCompany>Baker Hughes INTEQ</serviceCompany>
		<runNumber>12.3</runNumber>
		<creationDate>2001-06-18T13:20:00.000Z</creationDate>
		<description>Drilling Data Log</description>
		<indexType>date time</indexType>
		<stepIncrement uom="s">0</stepIncrement>
		<startDateTimeIndex>2001-06-18T13:20:00Z</startDateTimeIndex>
		<endDateTimeIndex>2001-06-18T14:20:00Z</endDateTimeIndex>
		<direction>increasing</direction>
		<indexCurve>Time</indexCurve>
		<nullValue>-999.25</nullValue>
		<logCurveInfo uid="lci-1">
			<mnemonic>Time</mnemonic>
			<classWitsml>time</classWitsml>
			<unit>m</unit>
			<mnemAlias>md</mnemAlias>
			<nullValue>-999.25</nullValue>
			<curveDescription>time stamp</curveDescription>
			<sensorOffset uom="ft">0</sensorOffset>
			<traceState>raw</traceState>
			<typeLogData>double</typeLogData>
		</logCurveInfo>
		<logCurveInfo uid="lci-2">
			<mnemonic>DVER</mnemonic>
			<classWitsml>TVD of hole</classWitsml>
			<unit>m</unit>
			<mnemAlias>tvd</mnemAlias>
			<nullValue>-999.25</nullValue>
			<curveDescription>Vertical depth</curveDescription>
			<sensorOffset uom="ft">0</sensorOffset>
			<traceState>raw</traceState>
			<typeLogData>double</typeLogData>
		</logCurveInfo>
		<logCurveInfo uid="lci-3">
			<mnemonic>DBTM</mnemonic>
			<classWitsml>measured depth of DST bottom</classWitsml>
			<unit>m</unit>
			<mnemAlias>distBit</mnemAlias>
			<nullValue>-999.25</nullValue>
			<curveDescription>Distance drilled by bit</curveDescription>
			<sensorOffset uom="ft">0</sensorOffset>
			<traceState>raw</traceState>
			<typeLogData>double</typeLogData>
		</logCurveInfo>
		<logCurveInfo uid="lci-4">
			<mnemonic>DTOR_RT</mnemonic>
			<classWitsml>torque (average)</classWitsml>
			<unit>kft.lbf</unit>
			<mnemAlias>tqOnBot</mnemAlias>
			<nullValue>-999.25</nullValue>
			<curveDescription>On bottom torque</curveDescription>
			<sensorOffset uom="ft">0</sensorOffset>
			<traceState>raw</traceState>
			<typeLogData>double</typeLogData>
		</logCurveInfo>
		<logCurveInfo uid="lci-5">
			<mnemonic>TQLS</mnemonic>
			<classWitsml>torque (average)</classWitsml>
			<unit>kft.lbf</unit>
			<mnemAlias>toOffBot</mnemAlias>
			<nullValue>-999.25</nullValue>
			<curveDescription>Off bottom torque</curveDescription>
			<sensorOffset uom="ft">0</sensorOffset>
			<traceState>raw</traceState>
			<typeLogData>double</typeLogData>
		</logCurveInfo>
				<logData>
			<mnemonicList>Time,DVER,DBTM,DTOR_RT,TQLS</mnemonicList>
			<unitList>s,m,m,kft.lbf,kft.lb</unitList>
			<data>2001-06-18T13:20:00.01Z,0,1.45,,</data>
			<data>2001-06-18T13:30:00.01Z,500,,0.01,1.42</data>
			<data>2001-06-18T13:40:00.03Z,501.02,,0.02,1.41</data>
			<data>2001-06-18T13:50:00.01Z,502,3.9,0.06,</data>
			<data>2001-06-18T14:00:00.01Z,503,4.9,0.11,1.48</data>
			<data>2001-06-18T14:10:00.05Z,504.04,5.94,0.18,1.55</data>
			<data>2001-06-18T14:20:00.03Z,,612.03,1.83,3.32</data>
		</logData>
		<commonData>
			<dTimCreation>2003-11-24T08:15:00.000Z</dTimCreation>
			<dTimLastChange>2003-11-24T08:15:00.000Z</dTimLastChange>
			<itemState>plan</itemState>
			<comments>These are the comments associated with the log object.</comments>
		</commonData>
		</log>
	</logs>]]>
         </XMLin>
         <OptionsIn xsi:type="xsd:string"></OptionsIn>
         <CapabilitiesIn xsi:type="xsd:string"/>
      </q1:WMLS_AddToStore>
   </soap:Body>
</soap:Envelope>

**Comment by TessForGithub2** [comment] 2019-06-26 19:17
Fixed and handed over to Sukhe for his next PR (branch 551) since it involved just commenting out 1 line of code.

There are 2 lingering concerns:

Even tho sending the data over to DoT resulted in the data being created (as proven by a subsequent GetFromStore), DoT returns a "500". 

Concern #1: Since there is no rollback, I thought we all agreed that if a ChannelSet is successfully created, even a failed attempt to add channels or add data will NOT result in -1. So, for QA that only can verify the "1" result, if the data (as in this case) results in DoT returning a 500 while still adding the data, QA will assume the data will be there. IT IS A FALSE POSITIVE should the 500 one day result in the data NOT being added. But if you think about it, our philosophy of "no rollback" locks us into this path.

There is no way for QA to granularize an error to a channel or data failure (only a channel set failure).

Concern #2: Why does DoT return a 500 (Internal Server Error) on data but data is successfully added?

So I will close this card but express these two concerns in a meeting where we can dissect it further.

**Comment by TessForGithub2** [comment] 2019-06-27 14:26
UPDATE: The errors need to be thrown by the Valve back with appropriate error codes. The log must reflect accurate error tracing so the root cause can always be uncovered. The strategy for repeating AddToStore is not viable as best as I can tell (it will result in a -409 error since a ChannelSet must be present & mappings happen each & every time an AddToStore occurs). The suggestion to just repeat Steps 2 & 3 (Add Channel & Add Data) as required is not a workable or desirable solution. Further discussion is required, and I will reopen this card.

**Comment by TessForGithub2** [comment] 2019-07-01 15:15
UPDATE: The only acceptable solution to this issue is to provide rollback.

The problems are:
1.  There are 3 REST calls on the SLB's API side for an AddToStore: channelSet, channels, & data.  
     However, on the WITSML API side, there is no concept of REST calls (knowledge of the solution 
     architecture is not necessary for the API to work). The WITSML API side expects a virtually 
     immediate "success" or "failure" of the entire query. So introducing delay in response causes a 
     timeout, and therefore a solution involving retry by Drillflow is not possible. It would cause more 
     confusion (errors) Client side.
2.  Retry as suggested by SLB only captures transient errors (network or DoT server down). There is 
     currently no Drillflow logic to discern transient vs. query errors, and due to #1 above, it is not 
     plausible.

I will open a new card that focuses on communicating the correct solution and providing more details of what it will take to provide rollback.

**Closed by TessForGithub2** 2019-07-01 15:15 UTC
Labels: API
