### ISSUE TITLE
DEV:LOG: Regression bug for get from store with open log query without log UID.

### ISSUE THREAD

**Issue by Mike-d-s** [hashmapinc/Drillflow#572] opened 2019-06-18 16:10 UTC
Epic: #361 
Size:
TBD

Regression bug for query logs without log UID to return all logs on server.

Repro Steps: 
1. Execute the following query:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<logs xmlns="http://www.witsml.org/schemas/1series"     
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.witsml.org/schemas/1series  ../xsd_schemas/obj_log.xsd" 
    version="1.4.1.1">
    <log uidWell="HM_manual-testing1234" uidWellbore="WB_test1" uid="">
        <nameWell></nameWell>
        <nameWellbore></nameWellbore>
        <name></name>
    </log>
</logs>
```
Server should return all of the logs available under a wellbore with only the requested elements (nameWell, nameWellbore, name) and the log UIDs.

Server currenly returns an unhandled REST backend error.

**Comment by TessForGithub2** [comment] 2019-07-24 16:27
Update: Sukhe confirmed this card can be closed because the fix is in.

**Closed by TessForGithub2** 2019-07-24 16:27 UTC
Labels: API, bug
